### ISSUE TITLE
pip can't install django-compressor

### ISSUE THREAD

**Issue by dicato** [rdegges/django-skel#10]
`pip install -r reqs/dev.txt` fails with the following error:

```
django-compressor has the version 1.2a2, which does not match the requirement django-compressor==dev (from -r reqs/common.txt (line 3))
```

Changing django-compressor to 1.2a2 fixes the issue.

**Comment by rdegges** [comment]
See my comments on #11 for a workaround, temporarily. This is a bug in `pip` (upstream).
