### ISSUE TITLE
Changing django-heroku-postgresify with dj-database-url?

### ISSUE THREAD

**Issue by mastrolinux** [rdegges/django-skel#14]
I suggest to change your django-heroku-postgresify package with the officially mentioned dj-database-url. The two packages are similar but the last is mentioned in the official doc page of heroku: https://devcenter.heroku.com/articles/django

**Comment by rdegges** [comment]
`django-heroku-postgresify` actually uses `dj-database-url`, but adds extra functionality so that `django-skel` can automatically create your `DATABASES` dict, and populate it with _all_ your databases automatically. This allows you to setup multi-database stuff a lot easier.
