### ISSUE TITLE
django-compressor==dev Causes Error When Installing for First Time

### ISSUE THREAD

**Issue by andrewaustin** [rdegges/django-skel#18]
Created new virtual environment, and changed requirements.txt to install dev requirements rather than prod. Then ran pip -r requirements.txt. Got the following error:

Downloading/unpacking django-compressor==dev (from -r reqs/common.txt (line 3))
Downloading develop (88Kb): 88Kb downloaded
Running setup.py egg_info for package django-compressor

  Source in /home/andrew/.virtualenvs/simplerunlog/build/django-compressor has the version 1.2, which does not match the requirement django-compressor==dev (from -r reqs/common.txt (line 3))
Source in /home/andrew/.virtualenvs/simplerunlog/build/django-compressor has version 1.2 that conflicts with django-compressor==dev (from -r reqs/common.txt (line 3))

Changing reqs/common.txt to django-compressor==1.2 fixed the issue.

**Comment by rdegges** [comment]
This was actually an old bug in pip causing issues. I previously _had_ to force django-compressor to the development release to get the desired functionality, but now that they've made a new release, this can be fixed forever >:)
