### ISSUE TITLE
Cannot import name abbrtask - Issue with django-celery in requirements

### ISSUE THREAD

**Issue by ratpik** [rdegges/django-skel#22]
Ran into this import issue post syncdb and migrate when I tied accessing localhost on the web url
#### Cannot import name abbrtask

_/venv/lib/python2.6/site-packages/djcelery/admin.py in <module>_
_from celery.utils import abbrtask_

Then came across this issue with sentry/django-celery here - https://github.com/getsentry/sentry/issues/538

So just upgraded django-celery to latest version (3.0.10) and things started to work. 
**pip install -U django-celery**

Perhaps you can upgrade the requirements file to reflect this?

**Comment by aladagemre** [comment]
I had the same problem. Suggested solution fixes it.

**Comment by rdegges** [comment]
This is totally fixed now, btw. Thank you for the help!
