### ISSUE TITLE
Running server within Eclipse got AttributrError

### ISSUE THREAD

**Issue by jaimevama** [rdegges/django-skel#24]
When I run the django server from within Eclipse i get

AttributeError: 'Settings' object has no attribute 'ROOT_URLCONF' 

It works fine from command line with or withoutt skel.

Any idea?

**Comment by rdegges** [comment]
Hrm, not sure. Probably a PYTHONPATH issue. I'm not an Eclipse user, so I can't really help :(

**Comment by jaimevama** [comment]
Fixed.
Thanks, rdegges.

I set woot.settings.dev in the option "Django settings module" and now it works.

saludos
jaime

**Comment by rdegges** [comment]
Awesome :D
