### ISSUE TITLE
django-storages Upgrade Breaks S3 Import

### ISSUE THREAD

**Issue by JeffPaine** [rdegges/django-skel#26]
`django-skel`'s prod.py has the following, relevant lines that work fine under `django-storages` 2.5.1:

``` python
from S3 import CallingFormat
AWS_CALLING_FORMAT = CallingFormat.SUBDOMAIN
```

However, after upgrading to 2.6.0,  the above code returns 

``` python
ImportError: No module named S3
```

Perhaps there's a reason for this or the mistake is simply on my end. Just something I noticed on my end today. Cheers!

**Comment by rdegges** [comment]
Bam, fixed. Thank you! >:)
