### ISSUE TITLE
[docs] Add docs for startapp

### ISSUE THREAD

**Issue by sethwoodworth** [rdegges/django-skel#29]
Because of the nested apps directory, creating a new app requires two steps.  This may not be obvious to new django users:

```
mkdir project_name/apps/APP_NAME
./manage.py startapp APP_NAME project_name/apps/APP_NAME
```

**Comment by rdegges** [comment]
You're totally right. I'll include that in the documentation. I'll mark this as closed once it is committed. Thank you!

**Comment by shrikant-joshi** [comment]
Isn't the following a valid alternative as well?

```
[.../~] $ cd /path/to/apps/
[.../apps] $ django-admin.py startapp APP_NAME
```
