### ISSUE TITLE
assets and static stub folders?

### ISSUE THREAD

**Issue by sethwoodworth** [rdegges/django-skel#30]
The `assets` and `static` folders are defined in `settings/common.py`.  IMO, if they are defined already in django settings, they could be added with placeholder files.  But git would require files to be placed inside the folders.  

How do you feel about adding placeholder files in these folders?  You already have a place where users delete your `docs` folder.

**Comment by jmcmanus** [comment]
The static folder is generated when you run collectstatic, and you generally don't store those collected files in source control, so why add it at all? 

As for the assets folder, you'd just be replacing the need to create the assets folder in the first place with the need to delete the placeholder contents. Doesn't seem like a huge improvement over the current setup. Just my two cents.

**Comment by rdegges** [comment]
Yah--I thought about this initially, but decided against it.

What some other people do is add a file like .empty to directories, but I really hate to clutter the filesystem with annoying things like that.
