### ISSUE TITLE
Questions regarding deployment

### ISSUE THREAD

**Issue by andyjessop** [rdegges/django-skel#32]
There are a few points that I don't think are covered in your documentation. I think the main one is regarding the database. The dev settings have an sqlite database, and it uses postgresify in the production environment to create a postgresql database - is this correct? At what stage does this happen and how do you change over the settings to the production settings?

Also, where are the postgresify and memecachify functions stored? I can't find them.

**Comment by cswenor** [comment]
When you follow the instructions all the way through you will see that you set environment variables on the heroku server to use the prod settings.
https://github.com/rdegges/django-skel/blob/master/project_name/settings/prod.py
it imports the common settings and then has special settings for production.
Also manage.py is set to use your dev settings.

**Comment by andrewaustin** [comment]
You are correct in that the dev settings use sqlite and production use postgresql.

The toggle between production and dev is set using an environment variable **DJANGO_SETTINGS_MODULE**.

To set this on heroku use:

```
heroku config:add DJANGO_SETTINGS_MODULE=myproject.settings.prod
```

Postgresify can be found at https://github.com/rdegges/django-heroku-postgresify
Memcachify is at https://github.com/rdegges/django-heroku-memcacheify

They are included in the prod.txt requirements file.

**Comment by andyjessop** [comment]
Thanks very much for your help guys. Very useful.
