### ISSUE TITLE
readme mentions Django 1.4 (and Django 1.5)

### ISSUE THREAD

**Issue by sesas** [rdegges/django-skel#38]
It's just a bit confusing but the readme mentions Django 1.5 at the top and then toward the middle it mentions that the installation steps assume you have Django 1.4 already installed. 

I'm wondering if that's a mistake or if it is intended (for migrations from Django 1.4 to 1.5) or so.

**Comment by andrewaustin** [comment]
It should say Django 1.5, I changed the one spot in the readme that still said Django 1.4. I cannot update the project description though, Randall will have to do that.

**Comment by sesas** [comment]
Thanks.

**Comment by daniellawrence** [comment]
I noticed the main description of the project is also "A modern Django (1.4) project skeleton".

This shows up on google, might be turning new users away :-1:

**Comment by rdegges** [comment]
Fixed this! Sorry for the delay, crazy busy lately.

You guys are the best! <3
