### ISSUE TITLE
Kombu for Celery development?

### ISSUE THREAD

**Issue by rclmenezes** [rdegges/django-skel#57]
Currently, in the docs, there is no obvious way to develop with Celery. Randall, do you have a preferred way? Would adding kombu in the reqs and the settings in development.py work for you?

Development.py

```
BROKER_URL = 'django://'

INSTALLED_APPS += (
    'debug_toolbar',
    'kombu.transport.django'
)
```

Edit: I'm going to close my own issue here, because I realized that CELERY_ALWAYS_EAGER means you don't need to set up a separate Celery worker to dev on your tasks. Sorry about the rubber duck. Perhaps clarifying this in the docs could be good?

**Comment by rdegges** [comment]
Hey there, get it figured out? Sorry for the delay.

**Comment by rclmenezes** [comment]
Yeah, I got it. Thanks!
