### ISSUE TITLE
Is this still active? 

### ISSUE THREAD

**Issue by chavenor** [rdegges/django-skel#66]
I see that the last commit was awhile back? 

Does it make sense to install Nginx in-front of Djanog  on Heroku as mentioned with this build-pack here?

https://github.com/ryandotsmith/nginx-buildpack

Thanks! 

Casey

**Comment by rdegges** [comment]
I'm not actively using Django in any real world projects right now, so haven't done a good job of maintaining this. If anyone wants to contribute, I'm 100% happy to support pull requests.

Regarding your question: I would not do that. There's really no need to put an entire NGINX reverse proxy in front of your Django app if you can use something like gunicorn (pure python) instead.

Just my two cents =)

**Comment by chavenor** [comment]
Oh.   Do you mind me asking what stack you moved too?

One of my sites is getting larger and looking to optimize.   Go Lang is
pretty interesting.   I also have started using tornado which has been
pretty solid.

Your thoughts?

**Comment by rdegges** [comment]
Yah! I still use quite a bit of stuff.

For personal projects, I use a lot of Flask. I still run a few production Django apps, but they don't require much work now-a-days.

For work, I also do a lot of node and express.

For crypto stuff, I've been doing more Go work. It's still not super nice for web development, but ideal for security style work =)

**Comment by rclmenezes** [comment]
Lately, I've been using reactGo as my go-to skeleton for new projects. It uses React, Redux and Express:
https://github.com/reactGo/reactGo

I've also heard good things about Este, which has also has react-native boilerplate, but it has a lot of moving parts in it:
https://github.com/este/este

If I specifically need Python (say, for an API I'm building that needs TensorFlow), then I just make it a separate service. docker-compose has been a godsend for developing on micro-services!
