### ISSUE TITLE
requirements in documentation not complete on ubuntu

### ISSUE THREAD

**Issue by kinkerl** [rdegges/django-skel#9]
Hi
to install the requirements on ubuntu 12.04, you have to install a lot of packages to make the pip install -r requirements.txt work:

sudo apt-get install libevent-dev postgresql libpq-dev memcached libmemcached-dev zlib1g-dev libssl-dev python-dev build-essential

And, of course.... you need django in installed to execute to use django-admin.py command. 
pip install django

Django is obvious but the other requirements were some pain to get together. Maybe you can update the docs.

**Comment by rdegges** [comment]
Heya, thank you! I was meaning to add this, but got busy and haven't thought about it since.

I'll try to get this updated today (I have to do some local testing on a fresh box to make sure I have the right requirements listed). Thanks again :)
